import MovieItem from "@/components/movie/movieItem/movieItem";
import { MovieInnerSkeletonCard } from "@/components/shared/skeletons/skeletons";
import { useEffect, useState } from "react";
import { env } from 'next.config';
import MainContainer from "@/components/shared/mainContainer/mainContainer";
import Head from "next/head";
import Image from "next/image";
import ReactPaginate from 'react-paginate';


const Trending = ()=>{
    const [trendingData, settrendingData] = useState(null);
    const [pageCount,setPageCount] = useState(1);
    const [loading, setLoading] = useState(false);
    const [mediaType, setMediaType] =useState('movie');
    const [timeWindow, setTimeWindow] =useState('day');
    const [filterActive, setFilterActive] = useState(0);
    const url = `${env.apiUrl}/trending/${mediaType}/${timeWindow}?api_key=${env.tmdbApiKey}`;
    const mainday = [
        {
            day: 'day'
        },
        {
            day: 'week'
        }
    ]
    const NextPage = ()=>{
        setPageCount(pageCount + 1)
        console.log(pageCount + 1)
        setTimeout(() => setLoading(true), 2000);
        fetch(url + `&page=${pageCount + 1}`)
        .then(response => response.json())
        .then(trendingData => {
            settrendingData(trendingData)
            console.log(trendingData)
        })
        setLoading(false)
    }
    const PrevPage = ()=>{
        setPageCount(pageCount - 1)
        console.log(pageCount - 1)
        setTimeout(() => setLoading(true), 2000);
        fetch(url + `&page=${pageCount - 1}`)
        .then(response => response.json())
        .then(trendingData => {
            settrendingData(trendingData)
            console.log(trendingData)
        })
    }
   
    useEffect(()=>{
        setTimeout(() => setLoading(true), 2000);
        fetch(`${env.apiUrl}/trending/movie/day?api_key=${env.tmdbApiKey}&page=1`)
        .then(response => response.json())
        .then(trendingData => {
            settrendingData(trendingData)
            console.log(trendingData)
        })
    },[])

    const getData = async(pageCount)=>{
        setTimeout(() => setLoading(true), 2000);
        const trendingDataResponse = await fetch(`${env.apiUrl}/trending/movie/${timeWindow}?api_key=${env.tmdbApiKey}&page=${pageCount}`)
        const ActualData = await trendingDataResponse.json()
        return ActualData
    }
        
    
    const handleClick = async(data)=>{
        console.log(data)        
        const currentPage = data.selected + 1
        const dataFromServe = await getData(currentPage)
        settrendingData(dataFromServe)
        
    }

    // const changeMediaType = (e)=>{  
    //     const setMediaType = e.target.value
    //     console.log(`${env.apiUrl}/trending/${setMediaType}/${timeWindow}?api_key=${env.tmdbApiKey}`)
    //     fetch(`${env.apiUrl}/trending/${setMediaType}/${timeWindow}?api_key=${env.tmdbApiKey}`)
    //     .then(response => response.json())
    //     .then(trendingData => {
    //         settrendingData(trendingData)
    //         console.log(trendingData)
    //     })
        
    // }
    const changeTimeWindowType = (e)=>{  
        const setTimeWindowType = e.target.value
        console.log(`${env.apiUrl}/trending/all/${setTimeWindowType}?api_key=${env.tmdbApiKey}`)
        fetch(`${env.apiUrl}/trending/all/${setTimeWindowType}?api_key=${env.tmdbApiKey}`)
        .then(response => response.json())
        .then(trendingData => {
            settrendingData(trendingData)
            console.log(trendingData)
        })

        
    }
    const HeroBackDrop = {
        backgroundImage : `url(${env.image_base_url}/original/${trendingData?.results?.[Math.floor(Math.random() * 20)]?.backdrop_path})`
    }
    
    return(
        <>
            <Head>
                <title>Trending Movies::Media</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="keywords"></meta>
                <link rel="icon" href="/images/favicon.ico" />
            </Head>
            {
                loading ? 
                <>
                    <div className="inner_hero_bg" style={HeroBackDrop}> 
                        <MainContainer>
                            <h1>Trending Movies</h1>
                        </MainContainer>
                    </div>
                    <MainContainer>
                        <div className="row_movie_wrapper"> 
                            <div className="main_grid_wrapper">
                                    <div className="filter_tab_warp d-flex align-items-center justify-content-end">
                                        <ul className="filter_tab d-flex align-items-center">
                                            {
                                                mainday.map((item,i)=>{
                                                    return(
                                                        <>
                                                            <li onClick={()=>setFilterActive(i)} className={filterActive === i ? 'active' : ''}><button onClick={changeTimeWindowType} value={item.day} >{item.day}</button></li>
                                                        </>
                                                    )
                                                })
                                            }
                                        </ul>
                                        {/* <select onChange={changeMediaType} name="" id="">
                                            <option value="all">all</option>
                                            <option value="movie">movie</option>
                                            <option value="tv">tv</option>
                                        </select> */}
                                    </div>
                                    
                                    {/* <button onClick={changeMediaType} value="tv">tv</button>
                                    <button onClick={changeMediaType} value="movie">Movies</button>
                                    <button onClick={changeMediaType} value="all">All</button> */}
                                <div className="grid">
                                    {
                                        trendingData?.results.map((item,i)=>{                                        
                                            return(
                                                <div key={i} className="portion">
                                                    <MovieItem item ={item} />
                                                </div>                
                                            )
                                        })
                                    }
                                </div>
                            </div>
                        </div>
                        <div className="next_prev_button_wrapper d-flex align-items-center justify-content-center">
                            {
                                pageCount > 1 ?
                                <button className="prev" onClick={PrevPage}><Image src="/images/left.png" fill={true} alt="icon" /> Prev</button>
                                :
                                <button className="prev" disabled><Image src="/images/left.png" fill={true} alt="icon" /> Prev</button>
                            }                    
                            <span className="pageCount">{pageCount}</span> of <span className="TotalpageCount">{trendingData?.total_pages}</span>
                            <button className="next" onClick={NextPage}>Next <Image src="/images/right.png" fill={true} alt="icon" /></button>
                        </div>

                        <div className="pagination_wrapper">
                            <ReactPaginate 
                                previousLabel =""
                                nextLabel = ""
                                breakLabel = "..."
                                pageRangeDisplayed={3}
                                pageCount={trendingData?.total_pages}
                                onPageChange={handleClick}
                                breakClassName="breakline"
                                breakLinkClassName="breakline_link"
                                pageClassName="page_item"
                                pageLinkClassName="page_item_link"
                                activeClassName="page_item_active"
                                activeLinkClassName="page_item_link_active"
                                previousClassName="previous"
                                nextClassName="next"
                                containerClassName={'pagination'}
                            />
                        </div>
                        
                        
                        
                    </MainContainer>
                </>
                :
                <div className="loading_div d-flex align-items-center justify-content-center">
                    <span className="loader"></span>
                </div>
            }
        </>
    )
}

export default Trending;


// export async function getServerSideProps(){
//     const responssMoviePopular = await fetch(`${env.apiUrl}/movie/popular?api_key=${env.tmdbApiKey}&page=2`);
//     const MovietrendingData = await responssMoviePopular.json();
//     return{
//       props:{
//         MovietrendingData: MovietrendingData,
//       }
//     }
//   }